name: planner_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  path_provider: ^2.1.2
  intl: ^0.18.1
  provider: ^6.1.2
  timezone: ^0.9.2
  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
